#!/bin/bash
# generate-docs.sh
# Regenerates auto-generated documentation from source code
#
# Usage: ./scripts/generate-docs.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_DIR="$(dirname "$DOCS_DIR")"

echo "=== CapiscIO Documentation Generator ==="
echo ""

# Check for gomarkdoc
if ! command -v gomarkdoc &> /dev/null && ! [ -f ~/go/bin/gomarkdoc ]; then
    echo "Installing gomarkdoc..."
    go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
fi

GOMARKDOC="${HOME}/go/bin/gomarkdoc"

# Generate Go API docs from capiscio-core
echo "📦 Generating Go API reference from capiscio-core..."
cd "$WORKSPACE_DIR/capiscio-core"
$GOMARKDOC ./pkg/... > "$DOCS_DIR/docs/reference/go-api-generated.md"

# Add header to generated file
cat > "$DOCS_DIR/docs/reference/go-api.md" << 'HEADER'
# Go API Reference

<!-- Code generated by gomarkdoc. DO NOT EDIT -->

!!! info "Auto-generated Documentation"
    This API reference is automatically generated from the Go source code in 
    [capiscio-core](https://github.com/capiscio/capiscio-core) using `gomarkdoc`.
    
    **Regenerate:** `./scripts/generate-docs.sh`

---

HEADER

# Append generated content (skip the first line which is the gomarkdoc comment)
tail -n +3 "$DOCS_DIR/docs/reference/go-api-generated.md" >> "$DOCS_DIR/docs/reference/go-api.md"
rm "$DOCS_DIR/docs/reference/go-api-generated.md"

echo "✅ Go API reference generated: docs/reference/go-api.md"

# Python SDK docs are auto-generated by mkdocstrings at build time
echo ""
echo "📦 Python SDK docs are generated at build time via mkdocstrings"
echo "   Source: $WORKSPACE_DIR/capiscio-sdk-python"

echo ""
echo "=== Done! ==="
echo ""
echo "Run 'mkdocs build' or 'mkdocs serve' to see the updated docs."
